[package]
name = "interledger-router"
version = "0.2.2-beta.2"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Router for Interledger requests"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/interledger-rs/interledger-rs"

[features]
default = ["trace"]
trace = ["tracing", "tracing-futures"]

[dependencies]
bytes = "0.4.12"
futures = "0.1.25"
interledger-packet = { path = "../interledger-packet", version = "^0.2.2-alpha.1"}
interledger-service = { path = "../interledger-service", version = "^0.2.2-alpha.1"}
log = "0.4.6"
parking_lot = "0.7.1"
tracing = { version = "0.1", optional = true }
tracing-futures = { version = "0.0.1-alpha.1", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
