[package]
name = "interledger-service"
version = "0.2.2-alpha.1"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "The core abstraction for the Interledger.rs implementation"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/interledger-rs/interledger-rs"

[dependencies]
futures = { version = "0.1.25", default-features = false }
interledger-packet = { path = "../interledger-packet", version = "^0.2.2-alpha.1"}
serde = { version = "1.0.99", default-features = false, features = ["derive"] }
base64 = { version = "0.10.1", default-features = false }
regex = { version = "1.2.1", default-features = false }
lazy_static = { version = "1.3.0", default-features = false }
unicase = { version = "2.4.0", default-features = false }
unicode-normalization = { version = "0.1.8", default-features = false }

[dev-dependencies]
serde_json = { version = "1.0.40", default-features = false }
