[package]
name = "interledger-stream"
version = "0.2.2-alpha.1"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Client and server implementations of the STREAM transport protocol"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/interledger-rs/interledger-rs"

# Optional feature to log connection statistics using a CSV file
[features]
metrics_csv = ["csv"]

[dependencies]
base64 = { version = "0.10.1", default-features = false }
bytes = { version = "0.4.12", default-features = false }
byteorder = { version = "1.3.1", default-features = false }
chrono = { version = "0.4.6", default-features = false }
csv = { version = "1.0.5", default-features = false, optional = true }
failure = { version = "0.1.5", default-features = false }
futures = { version = "0.1.25", default-features = false }
hex = { version = "0.3.2", default-features = false }
interledger-ildcp = { path = "../interledger-ildcp", version = "^0.2.2-alpha.1"}
interledger-packet = { path = "../interledger-packet", version = "^0.2.2-alpha.1"}
interledger-service = { path = "../interledger-service", version = "^0.2.2-alpha.1"}
log = { version = "0.4.6", default-features = false }
parking_lot = { version = "0.7.1", default-features = false }
ring = { version = "0.14.6", default-features = false }

[dev-dependencies]
env_logger = { version = "0.6.1", default-features = false }
interledger-router = { path = "../interledger-router", version = "^0.2.2-alpha.1"}
lazy_static = { version = "1.3.0", default-features = false }
regex = { version = "1.1.6", default-features = false }
tokio = { version = "0.1.16", default-features = false }
