name: Build and Test

on:
  push:
    paths-ignore:
      - "docs/**/*"
      - "scripts/**/*"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --all-targets --all-features
      - name: Install redis
        run: sudo apt install redis-server && redis-server --version
      - name: Run tests
        run: cargo test --all --all-features
        timeout-minutes: 10
